# Generated by Django 4.0.1 on 2022-03-24 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_alter_extended_user_profile_pic'),
    ]

    operations = [
        migrations.AddField(
            model_name='extended_user',
            name='type',
            field=models.BooleanField(default=True),
        ),
    ]
