# Generated by Django 4.0.1 on 2022-03-30 03:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_extended_user_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='NULL', max_length=80)),
                ('image', models.ImageField(blank=True, null=True, upload_to='static/core/profile')),
                ('category', models.CharField(default='NULL', max_length=80)),
                ('summary', models.TextField(blank=True, max_length=500)),
                ('content', models.TextField(blank=True, max_length=500)),
                ('draft', models.BooleanField(default=True)),
            ],
        ),
    ]
