# Generated by Django 4.0.1 on 2022-03-30 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_blog_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='draft',
            field=models.BooleanField(default=False),
        ),
    ]
