# Generated by Django 4.0.1 on 2022-04-01 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_alter_blog_draft'),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doctor', models.CharField(default='NULL', max_length=80)),
                ('patient', models.CharField(default='NULL', max_length=80)),
                ('speciality', models.CharField(default='NULL', max_length=80)),
                ('date', models.DateField()),
                ('time', models.TimeField()),
            ],
        ),
    ]
